<a href="https://colab.research.google.com/github/magish-gautam/Magish-Concept-of-AI/blob/Workshop-2/Worksheet_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#1
a1 = np.empty((2,2))
print("1. Empty 2x2:\n", a1)

#2
a2 = np.ones((4,2))
print("\n2. Ones 4x2:\n", a2)

#3
a3 = np.full((3,3), 7)
print("\n3. Full matrix (fill=7):\n", a3)

#4
arr = np.array([[1,2,3],[4,5,6]])
a4 = np.zeros_like(arr)
print("\n4. Zeros_like(arr):\n", a4)

#5
a5 = np.ones_like(arr)
print("\n5. Ones_like(arr):\n", a5)

#6
new_list = [1,2,3,4]
a6 = np.array(new_list)
print("\n6. List to numpy array:\n", a6)


1. Empty 2x2:
 [[3.80187788e-315 0.00000000e+000]
 [4.94065646e-324 6.60601795e-310]]

2. Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full matrix (fill=7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros_like(arr):
 [[0 0 0]
 [0 0 0]]

5. Ones_like(arr):
 [[1 1 1]
 [1 1 1]]

6. List to numpy array:
 [1 2 3 4]


In [2]:
#1
p1 = np.arange(10, 50)
print("1. 10 to 49:\n", p1)

#2
p2 = np.arange(9).reshape(3,3)
print("\n2. 3x3 0-8:\n", p2)

#3
p3 = np.eye(3)
print("\n3. Identity:\n", p3)

#4
p4 = np.random.random(30)
print("\n4. Mean of random 30:\n", p4.mean())

#5
p5 = np.random.random((10,10))
print("\n5. Min, Max:", p5.min(), p5.max())

#6
p6 = np.zeros(10)
p6[4] = 1
print("\n6. Zero array replace 5th with 1:\n", p6)

#7
arr = np.array([1,2,0,0,4,0])
p7 = arr[::-1]
print("\n7. Reverse array:\n", p7)

#8
p8 = np.ones((5,5))
p8[1:-1,1:-1] = 0
print("\n8. Border 1 inside 0:\n", p8)

#9
p9 = np.zeros((8,8))
p9[1::2, ::2] = 1
p9[::2, 1::2] = 1
print("\n9. Checkerboard:\n", p9)


1. 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 0-8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of random 30:
 0.5200471810969526

5. Min, Max: 0.018348142587626515 0.993993113721835

6. Zero array replace 5th with 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reverse array:
 [0 4 0 0 2 1]

8. Border 1 inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [3]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#1
print("1. x+y:\n", x+y)

#2
print("\n2. x-y:\n", x-y)

#3
print("\n3. x*3:\n", x*3)

#4
print("\n4. Square of x:\n", x**2)

#5
print("\n5. Dot products:")
print("v·w =", np.dot(v,w))
print("x·v =", x.dot(v))
print("x·y =\n", x.dot(y))

#6
print("\n6. Concatenate x & y (rows):\n", np.vstack((x,y)))
print("\nConcatenate v & w (columns):\n", np.column_stack((v,w)))

#7
try:
    print(np.concatenate((x,v)))
except Exception as e:
    print("\n7. Error Reason:", e)


1. x+y:
 [[ 6  8]
 [10 13]]

2. x-y:
 [[-4 -4]
 [-4 -3]]

3. x*3:
 [[ 3  6]
 [ 9 15]]

4. Square of x:
 [[ 1  4]
 [ 9 25]]

5. Dot products:
v·w = 219
x·v = [29 77]
x·y =
 [[19 22]
 [50 58]]

6. Concatenate x & y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v & w (columns):
 [[ 9 11]
 [10 12]]

7. Error Reason: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [4]:
import numpy as np

# Given matrices
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
print("A * A^-1 =\n", A.dot(np.linalg.inv(A)))

# 2. Prove AB != BA
print("\nAB =\n", A.dot(B))
print("\nBA =\n", B.dot(A))

# 3. Prove (AB)^T = B^T A^T
AB = A.dot(B)
print("\n(AB)^T =\n", AB.T)
print("\nB^T A^T =\n", B.T.dot(A.T))

# Linear equations:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

C = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

d = np.array([-1,-3,9])

# Solve using inverse
solution = np.linalg.inv(C).dot(d)
print("\nSolution of the system =\n", solution)


A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]

(AB)^T =
 [[23 51]
 [13 29]]

B^T A^T =
 [[23 51]
 [13 29]]

Solution of the system =
 [ 2.  1. -2.]
